### PR TITLE
tweak for perms plugins and fix russian words and...

### PR DESCRIPTION
**Pull request by TOWUK**
Please, add antispam locale variable [ upd: after I started writing a newsletter without having the rights to do so, an additional translation appeared in the config :) ]
<details>
  <summary>images (not actually)</summary>
да
да
</details>

---

finished tweak and fully correct translate
image
image

### CODE REVIEW

**Comment by TOWUK** [comment]
image

**Comment by TOWUK** [comment]
image

**Review by TheJeterLP — CHANGES_REQUESTED** [review]
Please don't change my standard config setup in config.java.

**Comment by TOWUK** [comment]
> Please don't change my standard config setup in config.java.

okay, sorry

**Comment by TheJeterLP** [comment]
So, are you going to change it back?

**Comment by TOWUK** [comment]
> So, are you going to change it back?

how it?

**Comment by TOWUK** [comment]
I did not understand how to do this, is there a completed translation in this topic? insert it yourself

**Comment by TOWUK** [comment]
its normal? okay?

**Comment by TOWUK** [comment]
i dont know how undo code

**Review by TheJeterLP — DISMISSED** [review]

**Comment by TheJeterLP** [comment]
Yes that's good, thanks

**Pull request merged**
